import { setupCache } from 'axios-cache-interceptor';
import { Document, OpenAPIClientAxios } from 'openapi-client-axios';

import type { Client } from '@/autogenerated.types';
import type { ClientOptions } from '@/typings';

export async function createClient(options: ClientOptions = {}): Promise<Client> {
  const { cacheOptions, baseURL, ...axiosOpts } = options;
  const definition = (await import('./api-docs.json')) as Document;

  const api = new OpenAPIClientAxios({
    definition: JSON.parse(JSON.stringify(definition)),
    axiosConfigDefaults: axiosOpts,
    withServer: {
      url: baseURL ?? 'https://api.jikan.moe/v4',
      description: 'Jikan REST API',
    },
  });

  await api.init();

  api.instance = setupCache(api.instance, cacheOptions);

  return api.getClient<Client>();
}
