import { AxiosRequestConfig } from 'axios';
import { OpenAPIClientAxios } from 'openapi-client-axios';

import type { Client } from './autogenerated.types';

// -------------------------

export async function createClient(options: AxiosRequestConfig = {}): Promise<Client> {
  const api = new OpenAPIClientAxios({
    definition:
      'https://raw.githubusercontent.com/jikan-me/jikan-rest/master/storage/api-docs/api-docs.json',
    axiosConfigDefaults: options as any,
  });

  return api.getClient<Client>();
}

// -------------------------

export type * from './autogenerated.types';
