import { AxiosRequestConfig } from 'axios';
import { OpenAPIClientAxios, type Document } from 'openapi-client-axios';

import type { Client } from './autogenerated.types';

// -------------------------

export async function createClient(options: AxiosRequestConfig = {}): Promise<Client> {
  const definition = (await import('./api-docs.json')) as Document;
  const api = new OpenAPIClientAxios({
    definition: Object.create(definition),
    axiosConfigDefaults: options as any,
  });

  return api.getClient<Client>();
}

// -------------------------

export type * from './autogenerated.types';
