import type { CacheOptions } from 'axios-cache-interceptor';
import type { AxiosRequestConfig } from 'openapi-client-axios';

import type { OperationMethods } from '@/autogenerated.types';

export interface ClientOptions extends AxiosRequestConfig {
  /**
   * **Axios Cache Options**
   * Options for cache.
   * @see https://axios-cache-interceptor.js.org/#/pages/configuration
   */
  cacheOptions?: Partial<CacheOptions>;
  /**
   * **Base URL**
   * Location of the JikanAPI. Leave empty to use the official JikanAPI instance.
   */
  baseURL?: string;
}

/**
 * Extracts the response data type from a specific operation method.
 *
 * @example
 * import type { OperationResponse } from 'jikan-api-ts';
 *
 * type AnimeInfo = OperationResponse<'getAnimeById'>;
 * type AnimeFullInfo = OperationResponse<'getAnimeFullById'>;
 */
export type OperationResponse<Operation extends keyof OperationMethods> =
  Operation extends keyof OperationMethods
    ? NonNullable<Awaited<ReturnType<OperationMethods[Operation]>>['data']['data']>
    : never;
